export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_USER = 'LOGIN_USER';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const INCREASE_INCREMENT = 'INCREASE_INCREMENT';
export const DECREASE_INCREMENT = 'DECREASE_INCREMENT';
